services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=paastech
      - POSTGRES_PASSWORD=paastech
      - POSTGRES_DB=paastech
    ports:
      - "5432:5432"
    volumes:
      - "data_db:/var/lib/postgresql/data"
      - "./database:/docker-entrypoint-initdb.d"

  git:
    build:
      context: git
    restart: always
    ports:
    - 22
    volumes:
      - "data_git:/srv"

  client:
    build:
      context: client
    restart: always
    stdin_open: true
    tty: true


volumes:
  data_db:
  data_git:
